# Generated by Django 6.0 on 2025-12-17 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200, verbose_name='Kata Kunci')),
                ('category', models.CharField(choices=[('judol', 'Judi Online'), ('obat_penguat', 'Obat Penguat'), ('obat_aborsi', 'Obat Aborsi'), ('konten_dewasa', 'Konten Dewasa'), ('penipuan', 'Penipuan'), ('lainnya', 'Lainnya')], default='lainnya', max_length=50, verbose_name='Kategori')),
                ('severity', models.CharField(choices=[('low', 'Rendah'), ('medium', 'Sedang'), ('high', 'Tinggi')], default='medium', max_length=20, verbose_name='Tingkat Keparahan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kata Kunci',
                'verbose_name_plural': 'Kata Kunci',
                'ordering': ['category', 'keyword'],
            },
        ),
        migrations.CreateModel(
            name='ScanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(verbose_name='URL Target')),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('running', 'Berjalan'), ('completed', 'Selesai'), ('failed', 'Gagal')], default='pending', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Mulai')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Selesai')),
                ('pages_scanned', models.IntegerField(default=0, verbose_name='Halaman Dipindai')),
                ('issues_found', models.IntegerField(default=0, verbose_name='Masalah Ditemukan')),
                ('error_message', models.TextField(blank=True, verbose_name='Pesan Error')),
                ('max_pages', models.IntegerField(default=100, verbose_name='Maksimum Halaman')),
                ('scan_subdomains', models.BooleanField(default=True, verbose_name='Pindai Subdomain')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sesi Pemindaian',
                'verbose_name_plural': 'Sesi Pemindaian',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('domain', models.CharField(max_length=200, verbose_name='Domain')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='Judul')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('content', models.TextField(blank=True, verbose_name='Konten')),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('scraped', 'Berhasil'), ('failed', 'Gagal')], default='pending', max_length=20, verbose_name='Status')),
                ('http_status', models.IntegerField(blank=True, null=True, verbose_name='HTTP Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Pesan Error')),
                ('scraped_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Scrape')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='detector.scansession', verbose_name='Sesi Pemindaian')),
            ],
            options={
                'verbose_name': 'Halaman Terscrape',
                'verbose_name_plural': 'Halaman Terscrape',
                'ordering': ['-scraped_at'],
                'unique_together': {('scan_session', 'url')},
            },
        ),
        migrations.CreateModel(
            name='DetectedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_text', models.CharField(max_length=200, verbose_name='Teks Tercocok')),
                ('context', models.TextField(verbose_name='Konteks')),
                ('category', models.CharField(max_length=50, verbose_name='Kategori')),
                ('severity', models.CharField(default='medium', max_length=20, verbose_name='Tingkat Keparahan')),
                ('location', models.CharField(default='content', max_length=50, verbose_name='Lokasi')),
                ('is_reported', models.BooleanField(default=False, verbose_name='Sudah Dilaporkan')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Sudah Ditangani')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Deteksi')),
                ('reported_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Dilaporkan')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Ditangani')),
                ('keyword', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='detector.keyword', verbose_name='Kata Kunci')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='detector.scrapedpage', verbose_name='Halaman')),
            ],
            options={
                'verbose_name': 'Konten Terdeteksi',
                'verbose_name_plural': 'Konten Terdeteksi',
                'ordering': ['-detected_at'],
            },
        ),
    ]
