# Generated by Django 6.0 on 2025-12-17 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('info', 'Info'), ('success', 'Berhasil'), ('warning', 'Peringatan'), ('error', 'Error')], default='info', max_length=20)),
                ('message', models.TextField()),
                ('url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='detector.scansession')),
            ],
            options={
                'verbose_name': 'Log Scan',
                'verbose_name_plural': 'Log Scan',
                'ordering': ['-created_at'],
            },
        ),
    ]
