# Generated by Django 6.0 on 2025-12-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_scanlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='scansession',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Dibatalkan'),
        ),
        migrations.AlterField(
            model_name='scansession',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu'), ('running', 'Berjalan'), ('completed', 'Selesai'), ('failed', 'Gagal'), ('cancelled', 'Dibatalkan')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
