# Generated by Django 6.0 on 2025-12-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0003_scansession_is_cancelled_alter_scansession_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('domain', models.CharField(blank=True, max_length=200, verbose_name='Domain')),
                ('keyword', models.CharField(blank=True, max_length=200, verbose_name='Keyword (opsional)')),
                ('whitelist_type', models.CharField(choices=[('url', 'URL Spesifik'), ('domain', 'Domain'), ('keyword_url', 'Keyword + URL')], default='url', max_length=20, verbose_name='Tipe Whitelist')),
                ('reason', models.TextField(blank=True, verbose_name='Alasan Whitelist')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Whitelist',
                'verbose_name_plural': 'Whitelist',
                'ordering': ['-created_at'],
            },
        ),
    ]
