# Generated by Django 6.0 on 2025-12-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0004_whitelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedcontent',
            name='confidence_score',
            field=models.FloatField(default=1.0, verbose_name='Skor Kepercayaan'),
        ),
        migrations.AddField(
            model_name='detectedcontent',
            name='is_false_positive',
            field=models.BooleanField(default=False, verbose_name='False Positive'),
        ),
        migrations.AddField(
            model_name='detectedcontent',
            name='safe_context_found',
            field=models.TextField(blank=True, verbose_name='Konteks Aman Ditemukan'),
        ),
    ]
