# Generated by Django 6.0.5 on 2026-05-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0005_detectedcontent_confidence_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedcontent',
            name='match_count',
            field=models.IntegerField(default=1, verbose_name='Jumlah Cocokan'),
        ),
        migrations.AddField(
            model_name='detectedcontent',
            name='sample_contexts',
            field=models.JSONField(blank=True, default=list, verbose_name='Contoh Konteks'),
        ),
        migrations.AddField(
            model_name='detectedcontent',
            name='unique_keywords',
            field=models.JSONField(blank=True, default=list, verbose_name='Kata Kunci Unik'),
        ),
        migrations.AddIndex(
            model_name='detectedcontent',
            index=models.Index(fields=['page', 'category'], name='detector_de_page_id_12f4b3_idx'),
        ),
        migrations.AddIndex(
            model_name='detectedcontent',
            index=models.Index(fields=['confidence_score'], name='detector_de_confide_2f7183_idx'),
        ),
        migrations.AddIndex(
            model_name='scanlog',
            index=models.Index(fields=['scan_session', '-created_at'], name='detector_sc_scan_se_6deaf1_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapedpage',
            index=models.Index(fields=['scan_session', 'status'], name='detector_sc_scan_se_60325c_idx'),
        ),
    ]
