# Generated by Django 6.0.5 on 2026-05-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0006_detectedcontent_match_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='strength',
            field=models.CharField(choices=[('decisive', 'Decisive — single match is high confidence'), ('strong', 'Strong — needs 1 corroborating keyword'), ('weak', 'Weak — needs ≥3 corroborating keywords or a decisive one')], default='strong', max_length=20, verbose_name='Kekuatan Kata Kunci'),
        ),
    ]
