# Generated by Django 6.0.5 on 2026-05-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0007_keyword_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedpage',
            name='content_hash',
            field=models.CharField(blank=True, max_length=40, verbose_name='Content SHA1'),
        ),
        migrations.AddField(
            model_name='scrapedpage',
            name='etag',
            field=models.CharField(blank=True, max_length=200, verbose_name='ETag'),
        ),
        migrations.AddField(
            model_name='scrapedpage',
            name='has_cloaking',
            field=models.BooleanField(default=False, verbose_name='Ada Cloaking'),
        ),
        migrations.AddField(
            model_name='scrapedpage',
            name='last_modified',
            field=models.CharField(blank=True, max_length=100, verbose_name='Last-Modified'),
        ),
        migrations.AlterField(
            model_name='scrapedpage',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu'), ('scraped', 'Berhasil'), ('failed', 'Gagal'), ('duplicate', 'Duplicate'), ('unchanged', 'Tidak Berubah'), ('skipped', 'Dilewati')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='scrapedpage',
            index=models.Index(fields=['url'], name='detector_sc_url_ca3e6f_idx'),
        ),
    ]
